import type { PropertyAgencyConfig } from "@/lib/property-agency/schemas";

const uid = () => crypto.randomUUID();

export function defaultSiteConfig(name: string): PropertyAgencyConfig {
  return {
    hero: {
      title: `Rumah Berkualitas dari ${name}`,
      subtitle:
        "Developer dan agen properti terpercaya — hunian premium siap huni dengan legalitas lengkap.",
      imageUrl: "",
      ctaPrimary: "Lihat Properti",
      ctaSecondary: "Hubungi Kami",
      showSearch: false,
    },
    about:
      `${name} fokus pada pengembangan dan penjualan hunian berkualitas. Setiap unit kami promosikan dengan transparansi harga, spesifikasi jelas, dan pendampingan penuh hingga serah terima.`,
    contact: {
      phone: "+62 812 3456 7890",
      email: "hello@agency.example",
      address: "Jl. Sudirman No. 10, Jakarta",
      whatsapp: "6281234567890",
      showForm: true,
    },
    listings: [
      {
        id: uid(),
        title: "Cluster Green Residence Tipe 45",
        location: "BSD City, Tangerang",
        price: 850_000_000,
        bedrooms: 2,
        bathrooms: 1,
        area: 45,
        landArea: 72,
        type: "Rumah",
        status: "sale",
        facilities: [
          "Carport",
          "Taman belakang",
          "One Gate System",
          "Jogging track",
          "Masjid & minimarket",
        ],
        description:
          "Hunian compact ideal untuk keluarga muda di kawasan BSD. Desain modern minimalis dengan ventilasi dan pencahayaan alami optimal.\n\nUnit siap huni dengan finishing berkualitas — keramik 60×60, kitchen set, dan instalasi listrik standar. Cluster tenang dengan keamanan 24 jam dan akses tol BSD hanya 5 menit.",
        specifications: [
          { label: "Tipe unit", value: "Tipe 45 / 2 KT" },
          { label: "Status", value: "Ready stock" },
          { label: "Sertifikat", value: "SHM (Sertifikat Hak Milik)" },
          { label: "Luas bangunan", value: "45 m²" },
          { label: "Luas tanah", value: "72 m²" },
          { label: "Kamar tidur", value: "2" },
          { label: "Kamar mandi", value: "1" },
          { label: "Carport", value: "1 mobil" },
          { label: "Lantai", value: "1 lantai" },
          { label: "Hadap", value: "Selatan" },
          { label: "Daya listrik", value: "2.200 VA" },
          { label: "Sumber air", value: "PDAM + sumur bor" },
          { label: "Tahun serah terima", value: "2025" },
          { label: "IMB / PBG", value: "Tersedia" },
          { label: "Hook-up AC", value: "2 unit (ruang tamu & master)" },
          { label: "Finishing", value: "Full furnished kitchen set" },
        ],
        imageUrl: "",
        floorPlanUrl: "",
        galleryUrls: [],
      },
      {
        id: uid(),
        title: "The Lavande Premium Tipe 120",
        location: "Pesanggrahan, Jakarta Selatan",
        price: 3_200_000_000,
        bedrooms: 4,
        bathrooms: 3,
        area: 120,
        landArea: 150,
        type: "Rumah",
        status: "sale",
        facilities: [
          "Smart Home System",
          "Private Pool",
          "Garasi 2 mobil",
          "Rooftop terrace",
          "Home office",
          "Taman depan & belakang",
        ],
        description:
          "Rumah premium 2 lantai dengan private pool dan smart home system. Lokasi strategis di Jakarta Selatan — 10 menit ke MRT, dekat sekolah internasional dan pusat bisnis TB Simatupang.\n\nInterior didesain oleh arsitek lokal ternama: lantai marmer di area publik, kaca tempered di balkon, dan sistem keamanan smart lock. Cocok untuk ekspatriat maupun keluarga executive.",
        specifications: [
          { label: "Tipe unit", value: "Tipe 120 / 4 KT" },
          { label: "Status", value: "Pre-launch (Q3 2025)" },
          { label: "Sertifikat", value: "SHM (Sertifikat Hak Milik)" },
          { label: "Luas bangunan", value: "120 m²" },
          { label: "Luas tanah", value: "150 m²" },
          { label: "Kamar tidur", value: "4 (1 master + 3 anak)" },
          { label: "Kamar mandi", value: "3 (2 di dalam + 1 tamu)" },
          { label: "Garasi", value: "2 mobil (tutup)" },
          { label: "Lantai", value: "2 lantai + rooftop" },
          { label: "Hadap", value: "Timur (pagi cerah)" },
          { label: "Private pool", value: "3 × 6 m (depth 1,2 m)" },
          { label: "Daya listrik", value: "5.500 VA" },
          { label: "Sumber air", value: "PDAM + water heater solar" },
          { label: "Tahun bangun", value: "2024" },
          { label: "IMB / PBG", value: "Tersedia & legal" },
          { label: "Smart home", value: "Lighting, CCTV, smart lock" },
          { label: "Finishing", value: "Premium — marmer & solid wood" },
        ],
        imageUrl: "",
        floorPlanUrl: "",
        galleryUrls: [],
      },
      {
        id: uid(),
        title: "Grand Wisata Cluster Montana Tipe 70",
        location: "Bekasi, Jawa Barat",
        price: 1_150_000_000,
        bedrooms: 3,
        bathrooms: 2,
        area: 70,
        landArea: 90,
        type: "Rumah",
        status: "sale",
        facilities: [
          "Club house",
          "Kolam renang cluster",
          "Lapangan badminton",
          "Keamanan 24 jam",
          "Akses tol JORR",
        ],
        description:
          "Rumah hook 2 lantai di township Grand Wisata — lingkungan keluarga dengan fasilitas lengkap. Dekat AEON Mall, sekolah favorit, dan stasiun LRT future line.\n\nCocok untuk first-time buyer yang ingin hunian luas dengan budget mid-range. Promo DP 10% dan free biaya KPR untuk 50 pembeli pertama.",
        specifications: [
          { label: "Tipe unit", value: "Montana Tipe 70 / 3 KT" },
          { label: "Status", value: "Indent (6 bulan)" },
          { label: "Sertifikat", value: "HGB → SHM (proses developer)" },
          { label: "Luas bangunan", value: "70 m²" },
          { label: "Luas tanah", value: "90 m² (hook)" },
          { label: "Kamar tidur", value: "3" },
          { label: "Kamar mandi", value: "2" },
          { label: "Carport", value: "1 mobil (+ ruang tambahan)" },
          { label: "Lantai", value: "2 lantai" },
          { label: "Hadap", value: "Barat" },
          { label: "Daya listrik", value: "3.500 VA" },
          { label: "Sumber air", value: "PDAM" },
          { label: "Estimasi serah terima", value: "Desember 2025" },
          { label: "IMB / PBG", value: "Dalam proses (developer)" },
          { label: "Promo", value: "Free AJB + BPHTB (periode terbatas)" },
        ],
        imageUrl: "",
        floorPlanUrl: "",
        galleryUrls: [],
      },
    ],
    categories: [
      { id: uid(), label: "Rumah Baru", icon: "🏗️", description: "Proyek launch terbaru" },
      { id: uid(), label: "Siap Huni", icon: "🏡", description: "Unit ready stock" },
      { id: uid(), label: "Cluster Premium", icon: "✨", description: "Kawasan eksklusif" },
      { id: uid(), label: "Investasi", icon: "📈", description: "Potensi capital gain" },
    ],
    howItWorks: [
      {
        id: uid(),
        step: 1,
        title: "Konsultasi",
        description: "Diskusi kebutuhan dan pilihan unit yang tersedia.",
      },
      {
        id: uid(),
        step: 2,
        title: "Survei Lokasi",
        description: "Kunjungi show unit dan kawasan proyek kami.",
      },
      {
        id: uid(),
        step: 3,
        title: "Booking & Serah Terima",
        description: "Proses pembelian aman dengan pendampingan legal.",
      },
    ],
    whyChooseUs: [
      {
        id: uid(),
        value: "15+",
        label: "Tahun pengalaman",
        description: "Terpercaya di industri properti",
      },
      {
        id: uid(),
        value: "500+",
        label: "Unit terjual",
        description: "Track record transaksi sukses",
      },
      {
        id: uid(),
        value: "100%",
        label: "Legal & aman",
        description: "Dokumen lengkap dan transparan",
      },
    ],
    agents: [
      {
        id: uid(),
        name: "Dewi Santoso",
        role: "Sales Manager",
        rating: 4.9,
        phone: "+62 812 1111 2222",
        imageUrl: "",
        listingsSold: 48,
      },
      {
        id: uid(),
        name: "Budi Hartono",
        role: "Property Consultant",
        rating: 4.8,
        phone: "+62 813 3333 4444",
        imageUrl: "",
        listingsSold: 36,
      },
    ],
    testimonials: [
      {
        id: uid(),
        name: "Rina Wijaya",
        role: "Pembeli unit BSD",
        quote:
          "Proses booking sampai serah terima sangat profesional. Spesifikasi rumah sesuai brosur dan timeline tepat.",
        rating: 5,
      },
      {
        id: uid(),
        name: "Andi Pratama",
        role: "Investor properti",
        quote:
          "Tim sales responsif dan transparan soal harga serta progress proyek. Highly recommended.",
        rating: 5,
      },
    ],
    popularAreas: [
      { id: uid(), name: "BSD City", listingCount: 0, imageUrl: "" },
      { id: uid(), name: "Bintaro", listingCount: 0, imageUrl: "" },
      { id: uid(), name: "Cibubur", listingCount: 0, imageUrl: "" },
      { id: uid(), name: "Depok", listingCount: 0, imageUrl: "" },
    ],
    blogPosts: [
      {
        id: uid(),
        title: "Tips Memilih Rumah untuk Keluarga Muda",
        excerpt:
          "Panduan praktis memilih tipe rumah, lokasi, dan fasilitas yang sesuai kebutuhan keluarga.",
        content:
          "Membeli rumah pertama adalah keputusan besar. Pertimbangkan jarak ke tempat kerja, fasilitas sekolah, dan akses transportasi.\n\nPastikan legalitas proyek jelas — cek IMB, sertifikat tanah, dan reputasi developer. Jangan ragu bertanya soal progress pembangunan dan jadwal serah terima.\n\nManfaatkan promo launching dan konsultasikan cicilan dengan tim sales kami untuk dapat penawaran terbaik.",
        category: "Tips",
        date: "2025-03-10",
        imageUrl: "",
      },
      {
        id: uid(),
        title: "Keuntungan Beli Rumah di Tahap Launching",
        excerpt:
          "Mengapa membeli di awal proyek bisa lebih menguntungkan dan apa yang perlu diperhatikan.",
        content:
          "Harga unit di tahap launching biasanya lebih kompetitif dibanding ready stock. Developer juga sering memberikan bonus DP ringan atau free biaya KPR.\n\nNamun, pastikan Anda memahami timeline pembangunan dan klausul di perjanjian jual beli. Kunjungi lokasi proyek dan lihat masterplan kawasan.\n\nTim kami siap mendampingi dari pemilihan unit hingga proses akad.",
        category: "Investasi",
        date: "2025-02-18",
        imageUrl: "",
      },
    ],
    mortgage: {
      enabled: false,
      defaultRate: 6.5,
      defaultTenorYears: 15,
    },
    footer: {
      tagline: "Partner terpercaya untuk hunian impian keluarga Indonesia.",
      facebook: "https://facebook.com",
      instagram: "https://instagram.com",
      linkedin: "",
      youtube: "",
      privacyUrl: "#",
      termsUrl: "#",
    },
    theme: { accent: "emerald", logoUrl: "", customColor: "" },
  };
}
