export const SITE_LABELS = {
  en: {
    home: "Home",
    about: "About",
    listings: "Properties",
    contact: "Contact",
    callUs: "Call us",
    viewDetail: "View details",
    backToListings: "Back to properties",
    listingNotFound: "Property not found.",
    descriptionTitle: "Description",
    specificationsTitle: "Specifications",
    facilitiesTitle: "Facilities",
    floorPlanTitle: "Floor plan",
    buildingArea: "building",
    landArea: "land",
    requestInfo: "Request info",
    viewProperties: "View properties",
    featuredTitle: "Our properties",
    listingsCount: "units",
    noListings: "No properties listed yet.",
    bed: "bed",
    bath: "bath",
    categoriesTitle: "Property collection",
    howItWorksTitle: "How to buy",
    whyChooseUsTitle: "Why choose us",
    agentsTitle: "Our sales team",
    listingsSold: "units sold",
    testimonialsTitle: "Client reviews",
    popularAreasTitle: "Project locations",
    blogTitle: "News & tips",
    readMore: "Read more",
    backToBlog: "Back to articles",
    blogNotFound: "Article not found.",
    aboutTitle: "About us",
    contactTitle: "Get in touch",
    contactFormName: "Your name",
    contactFormEmail: "Email",
    contactFormPhone: "Phone",
    contactFormMessage: "Message",
    contactFormSubmit: "Request consultation",
    contactFormThanks: "Thank you! We will contact you soon.",
    whatsapp: "WhatsApp",
    footerNav: "Navigation",
    footerLegal: "Legal",
    footerSocial: "Follow us",
    privacy: "Privacy policy",
    terms: "Terms of service",
    footer: "Built with Property Agency Builder.",
  },
  id: {
    home: "Beranda",
    about: "Tentang",
    listings: "Properti",
    contact: "Kontak",
    callUs: "Hubungi kami",
    viewDetail: "Lihat detail",
    backToListings: "Kembali ke properti",
    listingNotFound: "Properti tidak ditemukan.",
    descriptionTitle: "Deskripsi",
    specificationsTitle: "Spesifikasi",
    facilitiesTitle: "Fasilitas",
    floorPlanTitle: "Denah",
    buildingArea: "bangunan",
    landArea: "tanah",
    requestInfo: "Minta info",
    viewProperties: "Lihat properti",
    featuredTitle: "Properti kami",
    listingsCount: "unit",
    noListings: "Belum ada properti.",
    bed: "kt",
    bath: "km",
    categoriesTitle: "Koleksi properti",
    howItWorksTitle: "Cara membeli",
    whyChooseUsTitle: "Keunggulan kami",
    agentsTitle: "Tim sales kami",
    listingsSold: "unit terjual",
    testimonialsTitle: "Testimoni pelanggan",
    popularAreasTitle: "Lokasi proyek",
    blogTitle: "Berita & tips",
    readMore: "Baca selengkapnya",
    backToBlog: "Kembali ke artikel",
    blogNotFound: "Artikel tidak ditemukan.",
    aboutTitle: "Tentang kami",
    contactTitle: "Hubungi kami",
    contactFormName: "Nama Anda",
    contactFormEmail: "Email",
    contactFormPhone: "Telepon",
    contactFormMessage: "Pesan",
    contactFormSubmit: "Minta konsultasi",
    contactFormThanks: "Terima kasih! Kami akan segera menghubungi Anda.",
    whatsapp: "WhatsApp",
    footerNav: "Navigasi",
    footerLegal: "Legal",
    footerSocial: "Ikuti kami",
    privacy: "Kebijakan privasi",
    terms: "Syarat layanan",
    footer: "Dibuat dengan Property Agency Builder.",
  },
} as const;

export type SiteLabels = (typeof SITE_LABELS)[keyof typeof SITE_LABELS];
